CC = g++

solution: solution1 solution2 *input.txt

solution1: solution1.cpp
	$(CC) -o solution1 solution1.cpp

solution2: solution2.cpp
	$(CC) -o solution2 solution2.cpp

clean:
	rm -f \
	solution[12] \
	solution \
	alternate